use serde_json::{Map, Value};
use std::{
    collections::BTreeMap,
    env, fs,
    io::Write,
    path::{Path, PathBuf},
    process::{Command, ExitCode, Stdio},
};
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let arguments = arguments()?;
    let generated = generate(&arguments.schema_path)?;

    if let Some(output_path) = arguments.output_path {
        atomic_write(&output_path, generated.as_bytes())?;
    } else {
        print!("{generated}");
    }

    Ok(())
}

struct Arguments {
    schema_path: PathBuf,
    output_path: Option<PathBuf>,
}

fn arguments() -> Result<Arguments, String> {
    let mut arguments = env::args_os().skip(1);

    match (
        arguments.next(),
        arguments.next(),
        arguments.next(),
        arguments.next(),
        arguments.next(),
    ) {
        (Some(schema_flag), Some(schema_path), None, None, None) if schema_flag == "--schema" => {
            Ok(Arguments {
                schema_path: schema_path.into(),
                output_path: None,
            })
        }
        (Some(schema_flag), Some(schema_path), Some(output_flag), Some(output_path), None)
            if schema_flag == "--schema" && output_flag == "--output" =>
        {
            Ok(Arguments {
                schema_path: schema_path.into(),
                output_path: Some(output_path.into()),
            })
        }
        _ => Err(
            "usage: contract-generation-rust --schema <schema-path> [--output <output-path>]"
                .to_owned(),
        ),
    }
}

fn generate(schema_path: &Path) -> Result<String, String> {
    let source = fs::read_to_string(schema_path)
        .map_err(|error| format!("could not read schema {}: {error}", schema_path.display()))?;
    let mut schema: Value = serde_json::from_str(&source).map_err(|error| {
        format!(
            "schema {} is not valid JSON: {error}",
            schema_path.display()
        )
    })?;

    let definitions = definition_ids(&schema)?;
    strip_generated_provenance(&mut schema)?;
    normalize_schema(&mut schema, &definitions, "#")?;

    let root_schema = serde_json::from_value(schema)
        .map_err(|error| format!("normalized schema is not supported by schemars: {error}"))?;
    let mut type_space = TypeSpace::new(&TypeSpaceSettings::default());
    type_space
        .add_root_schema(root_schema)
        .map_err(|error| format!("typify rejected normalized schema: {error}"))?;

    format_rust(format!(
        "// @generated by @liiiraa/contract-generation.\n\
         // Source: packages/contracts-source/src/main.tsp\n\
         // This file is read-only. DO NOT EDIT.\n\n{}",
        type_space.to_stream()
    ))
}

fn atomic_write(path: &Path, contents: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("output path {} has no parent", path.display()))?;
    fs::create_dir_all(parent).map_err(|error| {
        format!(
            "could not create output directory {}: {error}",
            parent.display()
        )
    })?;
    let temporary_path = path.with_extension(format!(
        "{}.{}.tmp",
        path.extension()
            .and_then(|value| value.to_str())
            .unwrap_or("rs"),
        std::process::id()
    ));

    let result = (|| {
        fs::write(&temporary_path, contents).map_err(|error| {
            format!(
                "could not write temporary output {}: {error}",
                temporary_path.display()
            )
        })?;
        fs::rename(&temporary_path, path).map_err(|error| {
            format!(
                "could not atomically replace output {}: {error}",
                path.display()
            )
        })
    })();

    let _ = fs::remove_file(&temporary_path);
    result
}

fn definition_ids(root: &Value) -> Result<BTreeMap<String, String>, String> {
    if root.get("$schema").and_then(Value::as_str)
        != Some("https://json-schema.org/draft/2020-12/schema")
    {
        return Err("schema must declare JSON Schema Draft 2020-12".to_owned());
    }

    let definitions = root
        .get("$defs")
        .and_then(Value::as_object)
        .ok_or_else(|| "schema must contain object-valued '$defs'".to_owned())?;

    definitions
        .iter()
        .map(|(name, value)| {
            let expected_id = format!("{name}.json");
            let actual_id = value
                .get("$id")
                .and_then(Value::as_str)
                .ok_or_else(|| format!("definition '{name}' must declare '$id'"))?;

            if actual_id != expected_id {
                return Err(format!(
                    "definition '{name}' declares '$id' '{actual_id}', expected '{expected_id}'"
                ));
            }

            Ok((name.clone(), actual_id.to_owned()))
        })
        .collect()
}

fn strip_generated_provenance(schema: &mut Value) -> Result<(), String> {
    let object = schema
        .as_object_mut()
        .ok_or_else(|| "schema root must be an object".to_owned())?;
    let Some(provenance) = object.remove("x-liiiraa-generated") else {
        return Ok(());
    };
    let provenance = provenance
        .as_object()
        .ok_or_else(|| "'x-liiiraa-generated' must be an object".to_owned())?;

    let expected = [
        ("generator", "@liiiraa/contract-generation"),
        ("notice", "GENERATED FILE - DO NOT EDIT"),
        ("source", "packages/contracts-source/src/main.tsp"),
    ];

    if provenance.len() != expected.len()
        || expected
            .iter()
            .any(|(key, value)| provenance.get(*key).and_then(Value::as_str) != Some(*value))
    {
        return Err("generated provenance header is not recognized".to_owned());
    }

    Ok(())
}

fn normalize_schema(
    schema: &mut Value,
    definitions: &BTreeMap<String, String>,
    location: &str,
) -> Result<(), String> {
    let Some(object) = schema.as_object_mut() else {
        return Ok(());
    };
    normalize_string_constant_union(object, location)?;
    let keys = object.keys().cloned().collect::<Vec<_>>();

    for key in keys {
        match key.as_str() {
            "$defs" => {
                normalize_named_schemas(object, "$defs", definitions, location)?;
                let value = object
                    .remove("$defs")
                    .expect("schema key was collected from this object");
                if object.insert("definitions".to_owned(), value).is_some() {
                    return Err(format!(
                        "schema at '{location}' declares both '$defs' and 'definitions'"
                    ));
                }
            }
            "definitions" | "properties" => {
                normalize_named_schemas(object, &key, definitions, location)?;
            }
            "oneOf" | "anyOf" => {
                normalize_schema_array(object, &key, definitions, location)?;
            }
            "items" | "not" => {
                let value = object
                    .get_mut(&key)
                    .expect("schema key was collected from this object");
                normalize_schema(value, definitions, &format!("{location}/{key}"))?;
            }
            "$ref" => normalize_reference(object, definitions, location)?,
            "unevaluatedProperties" => normalize_closed_object(object, location)?,
            "const" => normalize_constant(object, location)?,
            "format" => normalize_format(object, location)?,
            "enum" => {
                if object
                    .get("enum")
                    .and_then(Value::as_array)
                    .is_none_or(Vec::is_empty)
                {
                    return Err(format!("'enum' at '{location}' must not be empty"));
                }
            }
            "$id" | "$schema" | "type" | "required" | "minLength" | "maxLength" | "minimum"
            | "maximum" | "minItems" | "maxItems" => {}
            "additionalProperties" => {
                if object.get(&key) != Some(&Value::Bool(false)) {
                    return Err(format!(
                        "unsupported JSON Schema keyword value 'additionalProperties' at '{location}'"
                    ));
                }
            }
            unsupported => {
                return Err(format!(
                    "unsupported JSON Schema keyword '{unsupported}' at '{location}'"
                ));
            }
        }
    }

    Ok(())
}

fn normalize_string_constant_union(
    object: &mut Map<String, Value>,
    location: &str,
) -> Result<(), String> {
    let Some(branches) = object.get("anyOf").and_then(Value::as_array) else {
        return Ok(());
    };

    let constants = branches
        .iter()
        .map(|branch| {
            let branch = branch.as_object()?;
            if branch.len() != 2 || branch.get("type").and_then(Value::as_str) != Some("string") {
                return None;
            }
            branch
                .get("const")
                .and_then(Value::as_str)
                .map(str::to_owned)
        })
        .collect::<Option<Vec<_>>>();
    let Some(constants) = constants else {
        return Ok(());
    };
    if constants.is_empty() {
        return Err(format!("'anyOf' at '{location}' must not be empty"));
    }

    let mut unique = constants.clone();
    unique.sort();
    unique.dedup();
    if unique.len() != constants.len() {
        return Err(format!(
            "string constant union at '{location}' contains duplicate values"
        ));
    }

    object.remove("anyOf");
    object.insert("type".to_owned(), Value::String("string".to_owned()));
    object.insert(
        "enum".to_owned(),
        Value::Array(constants.into_iter().map(Value::String).collect()),
    );
    Ok(())
}

fn normalize_format(object: &mut Map<String, Value>, location: &str) -> Result<(), String> {
    let format = object
        .remove("format")
        .and_then(|value| value.as_str().map(str::to_owned))
        .ok_or_else(|| format!("'format' at '{location}' must be a string"))?;

    if format != "date-time" {
        return Err(format!(
            "unsupported JSON Schema format '{format}' at '{location}'"
        ));
    }

    Ok(())
}

fn normalize_named_schemas(
    object: &mut Map<String, Value>,
    key: &str,
    definitions: &BTreeMap<String, String>,
    location: &str,
) -> Result<(), String> {
    let schemas = object
        .get_mut(key)
        .and_then(Value::as_object_mut)
        .ok_or_else(|| format!("'{key}' at '{location}' must be an object"))?;

    for (name, schema) in schemas {
        normalize_schema(schema, definitions, &format!("{location}/{key}/{name}"))?;
    }

    Ok(())
}

fn normalize_schema_array(
    object: &mut Map<String, Value>,
    key: &str,
    definitions: &BTreeMap<String, String>,
    location: &str,
) -> Result<(), String> {
    let schemas = object
        .get_mut(key)
        .and_then(Value::as_array_mut)
        .ok_or_else(|| format!("'{key}' at '{location}' must be an array"))?;

    if schemas.is_empty() {
        return Err(format!("'{key}' at '{location}' must not be empty"));
    }

    for (index, schema) in schemas.iter_mut().enumerate() {
        normalize_schema(schema, definitions, &format!("{location}/{key}/{index}"))?;
    }

    Ok(())
}

fn normalize_reference(
    object: &mut Map<String, Value>,
    definitions: &BTreeMap<String, String>,
    location: &str,
) -> Result<(), String> {
    let reference = object
        .get("$ref")
        .and_then(Value::as_str)
        .ok_or_else(|| format!("'$ref' at '{location}' must be a string"))?;
    let name = reference
        .strip_suffix(".json")
        .ok_or_else(|| format!("non-bundled '$ref' '{reference}' at '{location}'"))?;

    if definitions.get(name).map(String::as_str) != Some(reference) {
        return Err(format!("unresolved '$ref' '{reference}' at '{location}'"));
    }

    let pointer_name = name.replace('~', "~0").replace('/', "~1");
    object.insert(
        "$ref".to_owned(),
        Value::String(format!("#/definitions/{pointer_name}")),
    );
    Ok(())
}

fn normalize_closed_object(object: &mut Map<String, Value>, location: &str) -> Result<(), String> {
    let closure = object
        .remove("unevaluatedProperties")
        .expect("schema key was collected from this object");
    let is_false_schema = closure.as_object().is_some_and(|value| {
        value.len() == 1
            && value
                .get("not")
                .and_then(Value::as_object)
                .is_some_and(Map::is_empty)
    });

    if !is_false_schema {
        return Err(format!(
            "unsupported 'unevaluatedProperties' representation at '{location}'"
        ));
    }

    if object
        .insert("additionalProperties".to_owned(), Value::Bool(false))
        .is_some()
    {
        return Err(format!(
            "schema at '{location}' declares both object-closure keywords"
        ));
    }

    Ok(())
}

fn normalize_constant(object: &mut Map<String, Value>, location: &str) -> Result<(), String> {
    let constant = object
        .remove("const")
        .expect("schema key was collected from this object");

    if object
        .insert("enum".to_owned(), Value::Array(vec![constant]))
        .is_some()
    {
        return Err(format!(
            "schema at '{location}' declares both 'const' and 'enum'"
        ));
    }

    Ok(())
}

fn format_rust(source: String) -> Result<String, String> {
    let mut rustfmt = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("could not start pinned rustfmt: {error}"))?;

    rustfmt
        .stdin
        .take()
        .ok_or_else(|| "rustfmt stdin was not available".to_owned())?
        .write_all(source.as_bytes())
        .map_err(|error| format!("could not send generated Rust to rustfmt: {error}"))?;

    let output = rustfmt
        .wait_with_output()
        .map_err(|error| format!("could not wait for rustfmt: {error}"))?;

    if !output.status.success() {
        return Err(format!(
            "rustfmt rejected generated Rust: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    String::from_utf8(output.stdout)
        .map_err(|error| format!("rustfmt emitted non-UTF-8 output: {error}"))
}
