// eslint-disable-next-line @typescript-eslint/triple-slash-reference -- Phosphor 2.1.10 has an invalid NodeNext type export order.
/// <reference path="./phosphor-icons.d.ts" />

import {
  AppWindow as AppWindowIcon,
  ArrowCounterClockwise as ArrowCounterClockwiseIcon,
  ArrowRight as ArrowRightIcon,
  BatteryCharging as BatteryChargingIcon,
  Bell as BellIcon,
  Browsers as BrowsersIcon,
  CaretLeft as CaretLeftIcon,
  CaretRight as CaretRightIcon,
  ChartLineUp as ChartLineUpIcon,
  CheckCircle as CheckCircleIcon,
  CircleNotch as CircleNotchIcon,
  Circuitry as CircuitryIcon,
  ClockCounterClockwise as ClockCounterClockwiseIcon,
  Code as CodeIcon,
  Cpu as CpuIcon,
  Crosshair as CrosshairIcon,
  CrownSimple as CrownSimpleIcon,
  Database as DatabaseIcon,
  DesktopTower as DesktopTowerIcon,
  DownloadSimple as DownloadSimpleIcon,
  GameController as GameControllerIcon,
  Gauge as GaugeIcon,
  GearFine as GearFineIcon,
  Globe as GlobeIcon,
  GraphicsCard as GraphicsCardIcon,
  HardDrives as HardDrivesIcon,
  Info as InfoIcon,
  Key as KeyIcon,
  Lightning as LightningIcon,
  Link as LinkIcon,
  ListChecks as ListChecksIcon,
  LockKey as LockKeyIcon,
  MagnifyingGlass as MagnifyingGlassIcon,
  Memory as MemoryIcon,
  MinusCircle as MinusCircleIcon,
  Monitor as MonitorIcon,
  Network as NetworkIcon,
  Package as PackageIcon,
  Palette as PaletteIcon,
  PlugsConnected as PlugsConnectedIcon,
  Power as PowerIcon,
  Pulse as PulseIcon,
  PushPin as PushPinIcon,
  RocketLaunch as RocketLaunchIcon,
  Scan as ScanIcon,
  ShieldCheck as ShieldCheckIcon,
  SignOut as SignOutIcon,
  SlidersHorizontal as SlidersHorizontalIcon,
  Sparkle as SparkleIcon,
  Star as StarIcon,
  Storefront as StorefrontIcon,
  Thermometer as ThermometerIcon,
  Timer as TimerIcon,
  Toolbox as ToolboxIcon,
  Trash as TrashIcon,
  Usb as UsbIcon,
  UserCircle as UserCircleIcon,
  Warning as WarningIcon,
  Waveform as WaveformIcon,
  WifiHigh as WifiHighIcon,
  WindowsLogo as WindowsLogoIcon,
  X as XIcon,
} from '@phosphor-icons/react';

export type ProductIconWeight = 'bold' | 'duotone' | 'fill' | 'light' | 'regular' | 'thin';

const PRODUCT_ICONS = Object.freeze({
  activity: PulseIcon,
  app: AppWindowIcon,
  arrowRight: ArrowRightIcon,
  audio: WaveformIcon,
  battery: BatteryChargingIcon,
  bell: BellIcon,
  browser: BrowsersIcon,
  chart: ChartLineUpIcon,
  check: CheckCircleIcon,
  chevronLeft: CaretLeftIcon,
  chevronRight: CaretRightIcon,
  close: XIcon,
  code: CodeIcon,
  competitive: CrosshairIcon,
  cpu: CpuIcon,
  crosshair: CrosshairIcon,
  crown: CrownSimpleIcon,
  database: DatabaseIcon,
  device: DesktopTowerIcon,
  download: DownloadSimpleIcon,
  game: GameControllerIcon,
  gauge: GaugeIcon,
  globe: GlobeIcon,
  graphics: GraphicsCardIcon,
  hardDrive: HardDrivesIcon,
  history: ClockCounterClockwiseIcon,
  info: InfoIcon,
  key: KeyIcon,
  languages: GlobeIcon,
  lightning: LightningIcon,
  link: LinkIcon,
  list: ListChecksIcon,
  loading: CircleNotchIcon,
  lock: LockKeyIcon,
  logout: SignOutIcon,
  memory: MemoryIcon,
  microchip: CircuitryIcon,
  minus: MinusCircleIcon,
  monitor: MonitorIcon,
  network: NetworkIcon,
  package: PackageIcon,
  palette: PaletteIcon,
  pin: PushPinIcon,
  plugs: PlugsConnectedIcon,
  power: PowerIcon,
  profile: UserCircleIcon,
  radar: ScanIcon,
  recovery: ArrowCounterClockwiseIcon,
  rocket: RocketLaunchIcon,
  search: MagnifyingGlassIcon,
  services: GearFineIcon,
  settings: ToolboxIcon,
  shield: ShieldCheckIcon,
  sliders: SlidersHorizontalIcon,
  sparkle: SparkleIcon,
  star: StarIcon,
  store: StorefrontIcon,
  temperature: ThermometerIcon,
  timer: TimerIcon,
  toggles: SlidersHorizontalIcon,
  toolbox: ToolboxIcon,
  trash: TrashIcon,
  usb: UsbIcon,
  warning: WarningIcon,
  wifi: WifiHighIcon,
  windows: WindowsLogoIcon,
  zap: LightningIcon,
});

export type ProductIconName = keyof typeof PRODUCT_ICONS;

export interface ProductIconProps {
  readonly className?: string;
  readonly name: ProductIconName;
  readonly size?: number;
  readonly weight?: ProductIconWeight;
}

export const ProductIcon = ({
  className,
  name,
  size = 20,
  weight = 'regular',
}: ProductIconProps) => {
  const IconComponent = PRODUCT_ICONS[name];

  return (
    <span aria-hidden="true" className={['lb-product-icon', className].filter(Boolean).join(' ')}>
      <IconComponent size={size} weight={weight} />
    </span>
  );
};
