import { mkdir, mkdtemp, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  NodeHost,
  compile,
  formatDiagnostic,
  type CompilerOptions,
  type Namespace,
  type Program,
} from '@typespec/compiler';
import { compile as compileTypeScript } from 'json-schema-to-typescript';

type JsonObject = Record<string, unknown>;

export interface GeneratedArtifact {
  readonly path: string;
  readonly value: JsonObject | string;
}

export interface GenerationContext {
  readonly repositoryRoot: string;
  readonly sourceEntry: string;
  readonly outputRoot: string;
}

export interface GenerationStage {
  readonly name: string;
  generate(context: GenerationContext): Promise<readonly GeneratedArtifact[]>;
}

const REPOSITORY_ROOT = fileURLToPath(new URL('../../../', import.meta.url));
const SOURCE_ENTRY = join(REPOSITORY_ROOT, 'packages', 'contracts-source', 'src', 'main.tsp');
const STANDALONE_VALIDATOR_GENERATOR = join(
  REPOSITORY_ROOT,
  'packages',
  'contracts-ts',
  'scripts',
  'generate-standalone.mjs',
);
const STAGING_ROOT = process.env['LIIIRAA_GENERATION_STAGING_ROOT'];
const OUTPUT_ROOT =
  STAGING_ROOT === undefined
    ? join(REPOSITORY_ROOT, 'contracts', 'generated')
    : join(STAGING_ROOT, 'contracts', 'generated');
const DESKTOP_OUTPUT_ROOT = join(OUTPUT_ROOT, 'desktop', 'v1');
const CONTROL_PLANE_OUTPUT_ROOT = join(OUTPUT_ROOT, 'control-plane', 'v1');
const HTTP_OUTPUT_ROOT = join(OUTPUT_ROOT, 'http');
const WEB_OUTPUT_ROOT = join(OUTPUT_ROOT, 'web', 'v1');
const TYPESCRIPT_OUTPUT_ROOT = join(
  STAGING_ROOT ?? REPOSITORY_ROOT,
  'packages',
  'contracts-ts',
  'src',
  'generated',
);
const RUST_OUTPUT_ROOT = join(STAGING_ROOT ?? REPOSITORY_ROOT, 'crates', 'contracts-rust', 'src');

export const OUTPUT_PATHS = Object.freeze({
  messageEnvelope: join(DESKTOP_OUTPUT_ROOT, 'message-envelope.schema.json'),
  diagnosticValue: join(DESKTOP_OUTPUT_ROOT, 'diagnostic-value.schema.json'),
  inspectSystem: join(DESKTOP_OUTPUT_ROOT, 'inspect-system.schema.json'),
  shellMessage: join(DESKTOP_OUTPUT_ROOT, 'shell-message.schema.json'),
  controlPlaneDocument: join(CONTROL_PLANE_OUTPUT_ROOT, 'control-plane-document.schema.json'),
  webDocument: join(WEB_OUTPUT_ROOT, 'web-document.schema.json'),
  openApi: join(HTTP_OUTPUT_ROOT, 'openapi.json'),
  typescriptModels: join(TYPESCRIPT_OUTPUT_ROOT, 'models.ts'),
  typescriptIndex: join(TYPESCRIPT_OUTPUT_ROOT, 'index.ts'),
  rustModels: join(RUST_OUTPUT_ROOT, 'generated.rs'),
});

const KNOWN_OUTPUT_PATHS = new Set(Object.values(OUTPUT_PATHS).map((path) => resolve(path)));
const SCHEMA_DIALECT = 'https://json-schema.org/draft/2020-12/schema';
const GENERATED_HEADER = Object.freeze({
  generator: '@liiiraa/contract-generation',
  notice: 'GENERATED FILE - DO NOT EDIT',
  source: 'packages/contracts-source/src/main.tsp',
});
const GENERATED_TYPESCRIPT_HEADER = `/**
 * @generated by @liiiraa/contract-generation.
 * Source: packages/contracts-source/src/main.tsp
 * This file is read-only. DO NOT EDIT.
 */`;
const REQUIRED_DEFINITIONS = Object.freeze([
  'DiagnosticValue',
  'HostToRendererShellEvent',
  'InspectSystemRequest',
  'InspectSystemResult',
  'RendererToHostShellCommand',
  'ShellCloseContext',
  'ShellInstallerIdentity',
  'ShellNavigationIntent',
  'ShellNotificationCategory',
  'ShellNotificationPreference',
  'ShellStartupState',
  'ShellTrayPreference',
  'ShellWindowState',
  'WebIdentifier',
  'WebText',
  'WebPathnameTemplate',
  'WebUri',
  'Sha256Digest',
  'WebSurface',
  'WebShell',
  'IndexingPolicy',
  'ValidationState',
  'CapabilityAvailability',
  'SafeContextKey',
  'LocalePolicy',
  'WebSecurityBoundary',
  'OfficialReleaseOrigin',
  'SignatureState',
  'ScreenshotReviewState',
  'WebRouteRecord',
  'ClaimEvidence',
  'ContentRecord',
  'ScreenshotProvenance',
  'ReleaseArtifactEvidence',
  'ReleaseRecord',
  'FutureAuthorityCommand',
  'NoChangeReceipt',
  'AdminAuditEvent',
  'ControlPlaneDocument',
]);

const CONTROL_PLANE_DEFINITION_NAMES = Object.freeze([
  'ControlPlaneIdentifier',
  'ControlPlaneShortText',
  'RedactedAuthorityText',
  'AuthorityEtag',
  'ContractSchemaVersion',
  'OpaquePayloadBytes',
  'DetachedSignature',
  'CurrencyCode',
  'MoneyMinorUnits',
  'AuthorityProvenance',
  'AccountState',
  'SessionState',
  'AuthenticationStrength',
  'SubscriptionState',
  'SubscriptionPlan',
  'InvoiceState',
  'DeviceBindingState',
  'SupportCaseState',
  'ConsentState',
  'ConsentScope',
  'AdminRole',
  'AdminAction',
  'AccountCommandAction',
  'SessionCommandAction',
  'CommerceCommandAction',
  'DeviceCommandAction',
  'SupportCommandAction',
  'ConsentCommandAction',
  'AuthorityReceiptOutcome',
  'AuthorityErrorCode',
  'ProviderIdentity',
  'ProviderEventType',
  'AuditResult',
  'AuthorityProjectionMetadata',
  'AccountProjection',
  'SessionProjection',
  'SubscriptionProjection',
  'InvoiceProjection',
  'DeviceBindingProjection',
  'SupportCaseProjection',
  'DiagnosticConsent',
  'AccountCommand',
  'SessionCommand',
  'CommerceCommand',
  'DeviceCommand',
  'SupportCommand',
  'ConsentCommand',
  'AdminCommand',
  'AuthorityCommand',
  'AuthorityReceipt',
  'AuthorityError',
  'ProviderEvent',
  'AuditEvent',
  'OfflineEntitlementEnvelope',
  'AdminEnvironmentKind',
  'AdminDomain',
  'AdminFunction',
  'AdminFreshnessState',
  'AdminDensity',
  'AdminSavedViewVisibility',
  'AdminSeverity',
  'AdminInboxState',
  'AdminInvitationLifecycleState',
  'AdminInvitationDeliveryState',
  'AdminGovernanceKind',
  'AdminGovernanceState',
  'AdminMembershipState',
  'AdminStrongFactor',
  'AdminRiskLevel',
  'AdminJobType',
  'AdminJobState',
  'AdminIncidentState',
  'AdminConfigurationState',
  'AdminPrivacyRequestType',
  'AdminPrivacyCaseState',
  'AdminConflictState',
  'AdminOperationOutcome',
  'AdminOperationAction',
  'AdminEnvironmentIdentity',
  'AdminFreshness',
  'AdminProjectionMetadata',
  'AdminSafeRouteState',
  'AdminAccessContextProjection',
  'AdminSavedViewProjection',
  'AdminInboxItemProjection',
  'AdminInvitationProjection',
  'AdminInvitationCapacityProjection',
  'AdminGovernanceProjection',
  'AdminTeamMemberProjection',
  'AdminPermissionImpactProjection',
  'AdminJobProjection',
  'AdminIncidentProjection',
  'AdminConfigurationProjection',
  'AdminPrivacyCaseProjection',
  'AdminConflictProjection',
  'AdminPartialFailureItem',
  'AdminPartialFailureProjection',
  'AdminOperationReceipt',
  'AdminOperationCommand',
  'ControlPlaneDocument',
]);

const WEB_DEFINITION_NAMES = Object.freeze([
  'WebIdentifier',
  'WebText',
  'WebPathnameTemplate',
  'WebUri',
  'Sha256Digest',
  'WebSurface',
  'WebShell',
  'IndexingPolicy',
  'ValidationState',
  'CapabilityAvailability',
  'SafeContextKey',
  'LocalePolicy',
  'WebSecurityBoundary',
  'OfficialReleaseOrigin',
  'SignatureState',
  'ScreenshotReviewState',
  'WebRouteRecord',
  'ClaimEvidence',
  'ContentRecord',
  'ScreenshotProvenance',
  'ReleaseArtifactEvidence',
  'ReleaseRecord',
  'FutureAuthorityCommand',
  'NoChangeReceipt',
  'AdminAuditEvent',
]);

const WEB_DOCUMENT_ROOTS = Object.freeze([
  'WebRouteRecord',
  'ClaimEvidence',
  'ContentRecord',
  'ScreenshotProvenance',
  'ReleaseArtifactEvidence',
  'ReleaseRecord',
  'FutureAuthorityCommand',
  'NoChangeReceipt',
  'AdminAuditEvent',
]);

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => canonicalize(entry));
  }

  if (isJsonObject(value)) {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, canonicalize(entry)]),
    );
  }

  return value;
}

function stableJson(value: unknown): string {
  return `${JSON.stringify(canonicalize(value), null, 2)}\n`;
}

function requireControlPlaneOperations(program: Program): void {
  let namespace: Namespace = program.getGlobalNamespaceType();
  for (const segment of ['Liiiraa', 'Contracts', 'Desktop', 'V1']) {
    const nested = namespace.namespaces.get(segment);
    if (nested === undefined) {
      throw new Error(`Canonical TypeSpec namespace is missing ${segment}.`);
    }
    namespace = nested;
  }

  for (const operation of ['getAccount', 'issueAdminCommand']) {
    if (!namespace.operations.has(operation)) {
      throw new Error(`Canonical TypeSpec control-plane operation is missing ${operation}.`);
    }
  }
}

export function assertKnownOutputPath(path: string): void {
  const resolvedPath = resolve(path);
  if (!KNOWN_OUTPUT_PATHS.has(resolvedPath)) {
    throw new Error(`Refusing to write unowned generation path: ${resolvedPath}`);
  }
}

function expectRejectedPath(path: string): void {
  try {
    assertKnownOutputPath(path);
  } catch {
    return;
  }

  throw new Error(`Bounded path policy accepted forbidden path: ${path}`);
}

export function verifyBoundedPathPolicy(): void {
  for (const path of KNOWN_OUTPUT_PATHS) {
    assertKnownOutputPath(path);
  }

  expectRejectedPath(join(REPOSITORY_ROOT, 'package.json'));
  expectRejectedPath(join(OUTPUT_ROOT, 'unexpected.schema.json'));
  expectRejectedPath(join(OUTPUT_ROOT, '..', 'outside-generated.json'));
}

function requireDefinitions(bundle: JsonObject): JsonObject {
  const definitions = bundle['$defs'];
  if (!isJsonObject(definitions)) {
    throw new Error('TypeSpec JSON Schema bundle is missing $defs.');
  }

  for (const definitionName of REQUIRED_DEFINITIONS) {
    if (!isJsonObject(definitions[definitionName])) {
      throw new Error(`TypeSpec JSON Schema bundle is missing ${definitionName}.`);
    }
  }

  return definitions;
}

function collectReferencedDefinitionNames(value: unknown, names: Set<string>): void {
  if (Array.isArray(value)) {
    for (const entry of value) {
      collectReferencedDefinitionNames(entry, names);
    }
    return;
  }

  if (!isJsonObject(value)) {
    return;
  }

  const reference = value['$ref'];
  if (typeof reference === 'string' && reference.endsWith('.json')) {
    names.add(reference.slice(0, -'.json'.length));
  }

  for (const entry of Object.values(value)) {
    collectReferencedDefinitionNames(entry, names);
  }
}

function reachableDefinitions(
  definitions: JsonObject,
  rootNames: readonly string[],
  family: string,
): JsonObject {
  const selectedNames = new Set<string>(rootNames);
  const pendingNames = [...selectedNames];

  while (pendingNames.length > 0) {
    const name = pendingNames.pop();
    if (name === undefined) {
      continue;
    }

    const definition = definitions[name];
    if (!isJsonObject(definition)) {
      throw new Error(`TypeSpec JSON Schema bundle missing ${family} dependency ${name}.`);
    }

    const referencedNames = new Set<string>();
    collectReferencedDefinitionNames(definition, referencedNames);
    for (const referencedName of referencedNames) {
      if (!selectedNames.has(referencedName)) {
        selectedNames.add(referencedName);
        pendingNames.push(referencedName);
      }
    }
  }

  return Object.fromEntries(
    Object.entries(definitions).filter(([name]) => selectedNames.has(name)),
  );
}

function inspectionDefinitions(definitions: JsonObject): JsonObject {
  return reachableDefinitions(
    definitions,
    ['DiagnosticValue', 'InspectSystemRequest', 'InspectSystemResult'],
    'desktop inspection',
  );
}

function desktopDefinitions(definitions: JsonObject): JsonObject {
  return reachableDefinitions(
    definitions,
    [
      'DiagnosticValue',
      'HostToRendererShellEvent',
      'InspectSystemRequest',
      'InspectSystemResult',
      'RendererToHostShellCommand',
    ],
    'desktop',
  );
}

function webDefinitions(definitions: JsonObject): JsonObject {
  const selectedDefinitions = reachableDefinitions(definitions, WEB_DOCUMENT_ROOTS, 'web');

  for (const name of WEB_DEFINITION_NAMES) {
    if (!(name in selectedDefinitions)) {
      throw new Error(`Web document schema does not reach required definition ${name}.`);
    }
  }

  return selectedDefinitions;
}

function controlPlaneDefinitions(definitions: JsonObject): JsonObject {
  const emittedRoots = CONTROL_PLANE_DEFINITION_NAMES.filter((name) =>
    isJsonObject(definitions[name]),
  );
  return reachableDefinitions(definitions, emittedRoots, 'control-plane');
}

function createRuntimeSchema(
  schemaId: string,
  definitions: JsonObject,
  root: JsonObject,
): JsonObject {
  const referencedNames = new Set<string>();
  collectReferencedDefinitionNames(root, referencedNames);
  collectReferencedDefinitionNames(definitions, referencedNames);
  const unresolvedNames = [...referencedNames]
    .filter((name) => !(name in definitions))
    .sort((left, right) => left.localeCompare(right));
  if (unresolvedNames.length > 0) {
    throw new Error(
      `Runtime schema ${schemaId} has unresolved local references: ${unresolvedNames.join(', ')}.`,
    );
  }

  return {
    $schema: SCHEMA_DIALECT,
    $id: schemaId,
    'x-liiiraa-generated': GENERATED_HEADER,
    $defs: definitions,
    ...root,
  };
}

function inspectMessageRoot(): JsonObject {
  return {
    oneOf: [{ $ref: 'InspectSystemRequest.json' }, { $ref: 'InspectSystemResult.json' }],
  };
}

function shellMessageRoot(): JsonObject {
  return {
    oneOf: [{ $ref: 'HostToRendererShellEvent.json' }, { $ref: 'RendererToHostShellCommand.json' }],
  };
}

function transportMessageRoot(): JsonObject {
  return {
    oneOf: [
      { $ref: 'InspectSystemRequest.json' },
      { $ref: 'InspectSystemResult.json' },
      { $ref: 'HostToRendererShellEvent.json' },
      { $ref: 'RendererToHostShellCommand.json' },
    ],
  };
}

function webDocumentRoot(): JsonObject {
  return {
    oneOf: WEB_DOCUMENT_ROOTS.map((name) => ({ $ref: `${name}.json` })),
  };
}

function controlPlaneDocumentRoot(): JsonObject {
  return {
    $ref: 'ControlPlaneDocument.json',
  };
}

function toOpenApiSchema(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => toOpenApiSchema(entry));
  }

  if (!isJsonObject(value)) {
    return value;
  }

  const converted: JsonObject = {};
  for (const [key, entry] of Object.entries(value)) {
    if (key === '$id' || key === '$schema') {
      continue;
    }

    if (key === '$ref' && typeof entry === 'string' && entry.endsWith('.json')) {
      converted[key] = `#/components/schemas/${entry.slice(0, -'.json'.length)}`;
      continue;
    }

    converted[key] = toOpenApiSchema(entry);
  }

  return converted;
}

function createOpenApiDocument(definitions: JsonObject): JsonObject {
  const schemas = Object.fromEntries(
    Object.entries(definitions).map(([name, schema]) => [name, toOpenApiSchema(schema)]),
  );

  return {
    openapi: '3.1.0',
    info: {
      title: 'Liiiraa Boost Contracts',
      version: '1.2.0',
    },
    paths: {
      '/v1/account': {
        get: {
          operationId: 'getAccount',
          responses: {
            '200': {
              description: 'Authoritative account projection.',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AccountProjection' },
                },
              },
            },
            default: {
              description: 'Bounded redacted authority error.',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AuthorityError' },
                },
              },
            },
          },
        },
      },
      '/v1/admin/commands': {
        post: {
          operationId: 'issueAdminCommand',
          requestBody: {
            required: true,
            content: {
              'application/json': {
                schema: { $ref: '#/components/schemas/AdminCommand' },
              },
            },
          },
          responses: {
            '202': {
              description: 'Versioned authoritative receipt.',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AuthorityReceipt' },
                },
              },
            },
            default: {
              description: 'Bounded redacted authority error.',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AuthorityError' },
                },
              },
            },
          },
        },
      },
    },
    components: {
      schemas,
    },
    'x-liiiraa-generated': GENERATED_HEADER,
  };
}

async function compileCanonicalSchema(): Promise<JsonObject> {
  const stagingRoot = await mkdtemp(join(tmpdir(), 'liiiraa-contract-generation-'));
  const schemaStagingRoot = join(stagingRoot, 'schema');
  const bundlePath = join(schemaStagingRoot, 'desktop-v1.bundle.json');
  const compilerOptions: CompilerOptions = {
    emit: ['@typespec/json-schema'],
    options: {
      '@typespec/json-schema': {
        'emitter-output-dir': schemaStagingRoot,
        'file-type': 'json',
        'seal-object-schemas': true,
        bundleId: 'desktop-v1.bundle.json',
        emitAllRefs: true,
      },
    },
    outputDir: stagingRoot,
    warningAsError: true,
  };

  try {
    const program = await compile(NodeHost, SOURCE_ENTRY, compilerOptions);
    if (program.hasError()) {
      const diagnostics = program.diagnostics.map((diagnostic) => formatDiagnostic(diagnostic));
      throw new Error(`Canonical TypeSpec compilation failed:\n${diagnostics.join('\n')}`);
    }
    requireControlPlaneOperations(program);

    const emitted = JSON.parse(await readFile(bundlePath, 'utf8')) as unknown;
    if (!isJsonObject(emitted)) {
      throw new Error('TypeSpec emitted a non-object JSON Schema bundle.');
    }
    if (emitted['$schema'] !== SCHEMA_DIALECT) {
      throw new Error('TypeSpec emitted an unsupported JSON Schema dialect.');
    }

    requireDefinitions(emitted);
    return emitted;
  } finally {
    await rm(stagingRoot, { force: true, recursive: true });
  }
}

let canonicalSchemaPromise: Promise<JsonObject> | undefined;

function canonicalSchema(): Promise<JsonObject> {
  canonicalSchemaPromise ??= compileCanonicalSchema();
  return canonicalSchemaPromise;
}

const schemaStage: GenerationStage = {
  name: 'runtime-schemas-and-openapi',
  async generate(): Promise<readonly GeneratedArtifact[]> {
    const bundle = await canonicalSchema();
    const definitions = requireDefinitions(bundle);
    const legacyDesktopDefinitions = desktopDefinitions(definitions);
    const legacyInspectionDefinitions = inspectionDefinitions(legacyDesktopDefinitions);
    const standaloneControlPlaneDefinitions = controlPlaneDefinitions(definitions);
    const standaloneWebDefinitions = webDefinitions(definitions);

    return [
      {
        path: OUTPUT_PATHS.messageEnvelope,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/desktop/v1/message-envelope.schema.json',
          legacyInspectionDefinitions,
          inspectMessageRoot(),
        ),
      },
      {
        path: OUTPUT_PATHS.diagnosticValue,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/desktop/v1/diagnostic-value.schema.json',
          legacyInspectionDefinitions,
          { $ref: 'DiagnosticValue.json' },
        ),
      },
      {
        path: OUTPUT_PATHS.inspectSystem,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/desktop/v1/inspect-system.schema.json',
          legacyInspectionDefinitions,
          inspectMessageRoot(),
        ),
      },
      {
        path: OUTPUT_PATHS.shellMessage,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/desktop/v1/shell-message.schema.json',
          legacyDesktopDefinitions,
          shellMessageRoot(),
        ),
      },
      {
        path: OUTPUT_PATHS.controlPlaneDocument,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/control-plane/v1/control-plane-document.schema.json',
          standaloneControlPlaneDefinitions,
          controlPlaneDocumentRoot(),
        ),
      },
      {
        path: OUTPUT_PATHS.webDocument,
        value: createRuntimeSchema(
          'https://schemas.liiiraa.dev/web/v1/web-document.schema.json',
          standaloneWebDefinitions,
          webDocumentRoot(),
        ),
      },
      {
        path: OUTPUT_PATHS.openApi,
        value: createOpenApiDocument({
          ...legacyInspectionDefinitions,
          ...standaloneWebDefinitions,
          ...standaloneControlPlaneDefinitions,
        }),
      },
    ];
  },
};

function rebaseForTypeScript(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => rebaseForTypeScript(entry));
  }

  if (!isJsonObject(value)) {
    return value;
  }

  const rebased: JsonObject = {};

  for (const [key, entry] of Object.entries(value)) {
    if (key === '$ref' && typeof entry === 'string' && entry.endsWith('.json')) {
      rebased[key] = `#/$defs/${entry.slice(0, -'.json'.length)}`;
      continue;
    }

    if (
      key === 'unevaluatedProperties' &&
      isJsonObject(entry) &&
      isJsonObject(entry['not']) &&
      Object.keys(entry['not']).length === 0
    ) {
      rebased['additionalProperties'] = false;
      continue;
    }

    rebased[key] = rebaseForTypeScript(entry);
  }

  return rebased;
}

function normalizeGeneratedText(value: string): string {
  return `${value.replaceAll('\r\n', '\n').trimEnd()}\n`;
}

function normalizeForRustTransport(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((entry) => normalizeForRustTransport(entry));
  }

  if (!isJsonObject(value)) {
    return value;
  }

  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => key !== 'uniqueItems' && key !== 'pattern')
      .map(([key, entry]) => [key, normalizeForRustTransport(entry)]),
  );
}

const typescriptStage: GenerationStage = {
  name: 'typescript-transports',
  async generate(): Promise<readonly GeneratedArtifact[]> {
    const definitions = requireDefinitions(await canonicalSchema());
    const generatorSchema = rebaseForTypeScript({
      title: 'GeneratedContractRoots',
      type: 'object',
      properties: {
        messageEnvelope: transportMessageRoot(),
        webDocument: webDocumentRoot(),
        controlPlaneDocument: controlPlaneDocumentRoot(),
      },
      required: ['messageEnvelope', 'webDocument', 'controlPlaneDocument'],
      $defs: definitions,
    });

    if (!isJsonObject(generatorSchema)) {
      throw new Error('Could not build TypeScript transport generator schema.');
    }

    const models = await compileTypeScript(generatorSchema, 'GeneratedContractRoots', {
      additionalProperties: false,
      bannerComment: GENERATED_TYPESCRIPT_HEADER,
      style: {
        singleQuote: true,
      },
      unknownAny: false,
      unreachableDefinitions: true,
    });
    const transportAliases = [
      "export type MessageEnvelope = GeneratedContractRoots['messageEnvelope'];",
      "export type WebDocument = GeneratedContractRoots['webDocument'];",
      "export type ControlPlaneDocument = GeneratedContractRoots['controlPlaneDocument'];",
    ].join('\n');

    return [
      {
        path: OUTPUT_PATHS.typescriptModels,
        value: normalizeGeneratedText(`${models}\n${transportAliases}`),
      },
      {
        path: OUTPUT_PATHS.typescriptIndex,
        value: normalizeGeneratedText(
          `${GENERATED_TYPESCRIPT_HEADER}\n\nexport type * from './models.js';\nexport { controlPlaneDocumentValidator } from './standalone-validators.js';`,
        ),
      },
    ];
  },
};

function executeFile(
  command: string,
  arguments_: readonly string[],
  workingDirectory: string,
): Promise<string> {
  return new Promise((resolvePromise, rejectPromise) => {
    execFile(
      command,
      arguments_,
      {
        cwd: workingDirectory,
        encoding: 'utf8',
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true,
      },
      (error, stdout, stderr) => {
        if (error !== null) {
          rejectPromise(
            new Error(
              `${command} ${arguments_.join(' ')} failed:\n${stderr.trim() || error.message}`,
            ),
          );
          return;
        }

        resolvePromise(stdout);
      },
    );
  });
}

const rustStage: GenerationStage = {
  name: 'rust-transports',
  async generate(context): Promise<readonly GeneratedArtifact[]> {
    const definitions = requireDefinitions(await canonicalSchema());
    const stagingRoot = await mkdtemp(join(tmpdir(), 'liiiraa-contract-generation-rust-'));
    const schemaPath = join(stagingRoot, 'message-envelope.schema.json');

    try {
      await writeFile(
        schemaPath,
        stableJson(
          normalizeForRustTransport(
            createRuntimeSchema(
              'https://schemas.liiiraa.dev/desktop/v1/message-envelope.schema.json',
              definitions,
              transportMessageRoot(),
            ),
          ),
        ),
        'utf8',
      );

      const generated = await executeFile(
        'cargo',
        ['run', '--quiet', '--package', 'contract-generation-rust', '--', '--schema', schemaPath],
        context.repositoryRoot,
      );

      return [
        {
          path: OUTPUT_PATHS.rustModels,
          value: normalizeGeneratedText(generated),
        },
      ];
    } finally {
      await rm(stagingRoot, { force: true, recursive: true });
    }
  },
};

const GENERATION_STAGES: readonly GenerationStage[] = [schemaStage, typescriptStage, rustStage];

async function atomicWrite(path: string, contents: string): Promise<void> {
  assertKnownOutputPath(path);
  await mkdir(dirname(path), { recursive: true });
  const temporaryPath = `${path}.${String(process.pid)}.tmp`;

  try {
    await writeFile(temporaryPath, contents, 'utf8');
    await rename(temporaryPath, path);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

export async function generateContracts(): Promise<void> {
  verifyBoundedPathPolicy();

  const context: GenerationContext = {
    repositoryRoot: REPOSITORY_ROOT,
    sourceEntry: SOURCE_ENTRY,
    outputRoot: OUTPUT_ROOT,
  };

  const artifacts: GeneratedArtifact[] = [];
  for (const stage of GENERATION_STAGES) {
    const stageArtifacts = await stage.generate(context);
    for (const artifact of stageArtifacts) {
      assertKnownOutputPath(artifact.path);
      artifacts.push(artifact);
    }
  }

  const emittedPaths = new Set(artifacts.map((artifact) => resolve(artifact.path)));
  if (
    emittedPaths.size !== KNOWN_OUTPUT_PATHS.size ||
    [...KNOWN_OUTPUT_PATHS].some((path) => !emittedPaths.has(path))
  ) {
    throw new Error('Generation stages did not emit the exact owned output set.');
  }

  for (const artifact of artifacts) {
    await atomicWrite(
      artifact.path,
      typeof artifact.value === 'string' ? artifact.value : stableJson(artifact.value),
    );
  }

  await executeFile(process.execPath, [STANDALONE_VALIDATOR_GENERATOR], REPOSITORY_ROOT);
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (isDirectExecution) {
  if (process.argv.includes('--check-paths')) {
    verifyBoundedPathPolicy();
    console.log('Bounded contract-generation path policy passed.');
  } else {
    await generateContracts();
    console.log(`Generated ${String(KNOWN_OUTPUT_PATHS.size)} normalized contract artifacts.`);
  }
}
